DunningNotification/src/objects/Dunning_Notification_Definition__c.object
<CustomObject>
    <fields>
        <fullName>CC_Address__c</fullName>
        <description>CC Email Address</description>
        <inlineHelpText>CC Email Address</inlineHelpText>
        <label>CC Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CRON_Expression__c</fullName>
        <label>CRON Expression</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Email_Template_Name__c</fullName>
        <description>The default email template name for all phases, defined in Static Resources</description>
        <inlineHelpText>The default email template name for all phases, defined in Static Resources</inlineHelpText>
        <label>Default Email Template_Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Subject__c</fullName>
        <description>The default email subject for all dunning phases</description>
        <inlineHelpText>The default email subject for all dunning phases</inlineHelpText>
        <label>Default Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Name__c</fullName>
        <description>The From Name of the email</description>
        <inlineHelpText>The From Name of the email</inlineHelpText>
        <label>From Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reply_to_Address__c</fullName>
        <description>Reply-to Email Address</description>
        <inlineHelpText>Reply-to Email Address</inlineHelpText>
        <label>Reply-to Address</label>
        <type>Email</type>
    </fields>
    <label>Dunning Notification Definition</label>
    <nameField>
        <displayFormat>DunningDef-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dunning Notification Definition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DunningNotification/src/objects/DunningPhaseDef__c.object
<CustomObject>
    <fields>
        <fullName>Days__c</fullName>
        <description>How many days after the invoice is past-due should the notification be triggered</description>
        <inlineHelpText>How many days after the invoice is past-due should the notification be triggered</inlineHelpText>
        <label>Trigger After # of Days Past-Due</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DunningDef__c</fullName>
        <label>Dunning Notification</label>
        <referenceTo>Dunning_Notification_Definition__c</referenceTo>
        <relationshipLabel>Phases</relationshipLabel>
        <relationshipName>DunningPhases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email_Template_Name__c</fullName>
        <description>The email template name (stored in Static Resources).  If not specified, the default email template will be used.</description>
        <inlineHelpText>The email template name (stored in Static Resources).  If not specified, the default email template will be used.</inlineHelpText>
        <label>Email Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <description>The phase number</description>
        <inlineHelpText>The phase number</inlineHelpText>
        <label>Phase</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>The email subject for the current phase.  If not specified, the default email subject will be used.</description>
        <inlineHelpText>The email subject for the current phase.  If not specified, the default email subject will be used.</inlineHelpText>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dunning Notification Phase</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dunning Notification Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DunningNotification/src/classes/DunningNotificationService.cls
/**
 * Copyright (c) 2012 Zuora, Inc.
 * 
 * Author: tkung
 */
global with sharing class DunningNotificationService {

  private Dunning_Notification_Definition__c dunningDefHeader;
  private List < DunningPhaseDef__c > dunningPhaseDefs;
  private Map < Integer, String > emailTemplates;
  private List < Integer > dunningDays;

  private DunningNotificationJob job;

  global DunningNotificationService() {
    loadDunningDefinition();
    this.job = new DunningNotificationJob(
	    dunningDefHeader,
	    dunningPhaseDefs,
	    emailTemplates,
	    dunningDays);
  }

  global void scheduleJob() {
    System.schedule('Dunning Notification Service', this.dunningDefHeader.CRON_Expression__c, this.job);
  }

  public DunningNotificationJob getJob() {
    return this.job;
  }

  /**
   * Loads the email dunning notification definition and the dunning notification phases definition.
   * 
   * For each dunning phase: 
   * If the email template name is empty, default the email template name from the header definition.  
   * If the email subject is empty, default the email subject from the header definition.
   */
  private void loadDunningDefinition() {
    this.dunningDefHeader = [
	    SELECT id, Default_Subject__c, Default_Email_Template_Name__c, CRON_Expression__c
	    FROM Dunning_Notification_Definition__c LIMIT 1];
    if (this.dunningDefHeader == null) {
      throw new DunningNotificationException('There is no dunning definition defined. ');
    }

    Id dunningDefId = this.dunningDefHeader.Id;
    this.dunningPhaseDefs = [
	    SELECT Phase__c, Days__c, Email_Template_Name__c, Subject__c,
	      DunningDef__r.From_Name__c,
	      DunningDef__r.CC_Address__c,
	      DunningDef__r.Reply_To_Address__c
	    FROM DunningPhaseDef__c
	    WHERE DunningDef__c = : dunningDefId
	    ORDER BY phase__c];
    if (this.dunningPhaseDefs == null || this.dunningPhaseDefs.size() == 0) {
      throw new DunningNotificationException('There are no dunning phases defined. ');
    }

    dunningDays = new List < Integer > ();
    emailTemplates = new Map < Integer, String > ();

    for (DunningPhaseDef__c dunningPhase: dunningPhaseDefs) {
      System.debug('tina dunningPhase = ' + dunningPhase);
      Integer days = dunningPhase.days__c.intValue();
      dunningDays.add(days);
      if (dunningPhase.Subject__c == null || ''.equals(dunningPhase.Subject__c.trim())) {
        dunningPhase.Subject__c = this.dunningDefHeader.Default_Subject__c;
      }
      if (dunningPhase.Email_Template_Name__c == null || ''.equals(dunningPhase.Email_Template_Name__c.trim())) {
        dunningPhase.Email_Template_Name__c = this.dunningDefHeader.Default_Email_Template_Name__c;
      }

      String emailTemplateFileName = dunningPhase.Email_Template_Name__c;
      PageReference template = new PageReference('/resource/' + emailTemplateFileName);
      if (template == null) {
        throw new DunningEmailController.DunningEmailServiceException('An error occurred while loading email template from static resources: ' + emailTemplateFileName);
      }
      this.emailTemplates.put(dunningPhase.Phase__c.intValue(), Test.isRunningTest() ? '<BillToContactName>\n<MergeTablePastDueInvoice>' : template.getContent().toString());
    }
  }

  global class DunningNotificationException extends Exception {}
}